version: '3.8'

services:
  tube-tik-downloader:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
